OBJS += crc.o
OBJS += ibm.o
OBJS += vectors.o
OBJS += string.o
OBJS += stm32f10x.o
OBJS += time.o
OBJS += timer.o
OBJS += util.o
OBJS += console.o
OBJS += led_7seg.o
OBJS += mfm.o
OBJS += fm.o
OBJS += da.o
OBJS += amiga.o

OBJS-$(quickdisk) += quickdisk.o

OBJS-$(shugart) += floppy.o
OBJS-$(shugart) += main.o

SUBDIRS += gotek
